### ISSUE TITLE
reindex-index-data error on centos

### ISSUE THREAD

**Issue by jlong2git** [artefactual/archivematica-devtools#53]
Traceback (most recent call last):
  File "/opt/archivematica/libexec/archivematica/reindex-index-data", line 29, in <module>
    import elasticSearchFunctions
  File "/usr/lib/archivematica/archivematicaCommon/elasticSearchFunctions.py", line 39, in <module>
    from main.models import File, Transfer
  File "/usr/share/archivematica/dashboard/main/models.py", line 34, in <module>
    from django_extensions.db.fields import UUIDField
ImportError: cannot import name UUIDField

**Comment by jlong2git** [comment]
I had to downgrade django_extensions
warnings.warn("Django 1.8 features a native UUIDField, this UUIDField will be removed after Django 1.7 becomes unsupported.", DeprecationWarning

How do you get rid of the red circle with number of Tranfers if they where deleted on failure
I tried "am reindex-index-data transfers", I guess these tools simply don't work on CENTOS
I get this error 

Traceback (most recent call last):
  File "/usr/local/libexec/archivematica/reindex-index-data", line 99, in <module>
    sys.exit(reindex(args.index, index_doctypes[args.index], args.chunk_size))
  File "/usr/local/libexec/archivematica/reindex-index-data", line 69, in reindex
    doctype_records[doc_type] = [r['_source'] for r in elasticsearch.helpers.scan(conn, index=index, doc_type=doc_type, scroll='15m')]
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 403, in scan
    client.clear_scroll(body={'scroll_id': [scroll_id]}, ignore=(404, ))
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 1013, in clear_scroll
    params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 163, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError
